/* ═══════════════════════════════════════════
   BAZA DANYCH GRY — pytania i słowa
   ═══════════════════════════════════════════ */

// Faza 1: Uzupełnij brakujące słowo (50 zdań)
const QUESTIONS = [
    { sentence: "Mama piecze ___ na urodziny.",                answer: "tort",       hint: "Coś słodkiego ze świeczkami" },
    { sentence: "W nocy na niebie świeci ___.",                answer: "księżyc",    hint: "Jest okrągły i jasny" },
    { sentence: "Pies macha ___ na powitanie.",                answer: "ogonem",     hint: "Pies ma to z tyłu" },
    { sentence: "Rano jem ___ na śniadanie.",                  answer: "kanapkę",    hint: "Coś z chlebem" },
    { sentence: "___ mieszka w lesie i zbiera orzechy.",       answer: "wiewiórka",  hint: "Małe rude zwierzątko z puszystym ogonem" },
    { sentence: "Dzieci bawią się na ___.",                    answer: "podwórku",   hint: "Miejsce przed domem do zabawy" },
    { sentence: "Zimą pada biały ___.",                        answer: "śnieg",      hint: "Można z niego lepić bałwana" },
    { sentence: "Kot pije ___ z miski.",                       answer: "mleko",      hint: "Biały napój" },
    { sentence: "Tata czyta ___ przed snem.",                  answer: "bajkę",      hint: "Historia z książki" },
    { sentence: "___ pływa w stawie.",                         answer: "żaba",       hint: "Zielona i kumka" },
    { sentence: "W szkole piszemy w ___.",                     answer: "zeszycie",   hint: "Ma kartki w linie lub kratkę" },
    { sentence: "Ptaki budują ___ na drzewie.",                answer: "gniazdo",    hint: "Dom dla ptaków" },
    { sentence: "Samochód jedzie po ___.",                     answer: "drodze",     hint: "Asfaltowa nawierzchnia" },
    { sentence: "Ryby pływają w ___.",                         answer: "morzu",      hint: "Duży zbiornik słonej wody" },
    { sentence: "Słońce wschodzi ___.",                        answer: "rano",       hint: "Pora dnia, kiedy się budzimy" },
    { sentence: "___ daje nam miód.",                          answer: "pszczoła",   hint: "Latający owad w żółto-czarne paski" },
    { sentence: "Na obiad jemy ___ z klopsikami.",             answer: "makaron",    hint: "Długie lub krótkie, gotowane w wodzie" },
    { sentence: "W zimie nosimy czapkę i ___.",                answer: "szalik",     hint: "Owijamy nim szyję" },
    { sentence: "Babcia robi na drutach ___.",                 answer: "sweter",     hint: "Ciepłe ubranie wkładane przez głowę" },
    { sentence: "Listonosz przynosi ___.",                     answer: "listy",      hint: "Wkłada je do skrzynki pocztowej" },
    { sentence: "___ lata i ma kolorowe skrzydła.",            answer: "motyl",      hint: "Lubi siadać na kwiatach" },
    { sentence: "Chłopiec jedzie na ___ do szkoły.",           answer: "rowerze",    hint: "Jednoślad z dwoma kołami" },
    { sentence: "Kura znosi ___ w gnieździe.",                 answer: "jajka",      hint: "Okrągłe, w twardej skorupce" },
    { sentence: "Astronauta leci w ___.",                      answer: "kosmos",     hint: "Tam są gwiazdy i planety" },
    { sentence: "___ ma osiem nóg i plecie sieć.",             answer: "pająk",      hint: "Łapie muchy w pajęczynę" },
    { sentence: "Słoń ma długą ___.",                          answer: "trąbę",      hint: "Używa jej do picia wody" },
    { sentence: "___ jest królem wszystkich zwierząt.",        answer: "lew",        hint: "Duży kot z grzywą" },
    { sentence: "Lekarz leczy ___.",                           answer: "chorych",    hint: "Osoby, które się źle czują" },
    { sentence: "Strażak gasi ___.",                           answer: "pożar",      hint: "Wielki ogień, który się rozprzestrzenia" },
    { sentence: "Pilot steruje ___.",                          answer: "samolotem",  hint: "Wielki pojazd latający" },
    { sentence: "Nauczyciel pisze na ___.",                    answer: "tablicy",    hint: "Czarna lub biała powierzchnia w klasie" },
    { sentence: "W bibliotece wypożyczamy ___.",               answer: "książki",    hint: "Mają kartki i opowiadają historię" },
    { sentence: "___ ma długą szyję i je liście z drzew.",     answer: "żyrafa",     hint: "Najwyższe zwierzę na świecie" },
    { sentence: "Na plaży budujemy zamki z ___.",              answer: "piasku",     hint: "Drobne żółte ziarnka na plaży" },
    { sentence: "Zegar mierzy ___.",                           answer: "czas",       hint: "Godziny, minuty i sekundy" },
    { sentence: "Księżniczka mieszka w wysokim ___.",          answer: "zamku",      hint: "Budowla z wieżyczkami i fosą" },
    { sentence: "___ kroczy wolno i nosi dom na grzbiecie.",   answer: "żółw",       hint: "Gad z twardą skorupą" },
    { sentence: "Kucharz gotuje zupę w ___.",                  answer: "garnku",     hint: "Duże metalowe naczynie z pokrywką" },
    { sentence: "Pociąg jedzie po ___.",                       answer: "torach",     hint: "Metalowe szyny na podłożu" },
    { sentence: "Bałwan ma marchewkę zamiast ___.",            answer: "nosa",       hint: "Środkowa część twarzy, wąchamy nim" },
    { sentence: "Oczami ___.",                                 answer: "widzimy",    hint: "Co robimy za pomocą oczu?" },
    { sentence: "Uszami ___.",                                 answer: "słyszymy",   hint: "Co robimy za pomocą uszu?" },
    { sentence: "Piłkarz kopie ___ do bramki.",                answer: "piłkę",      hint: "Okrągły przedmiot do gry w nogę" },
    { sentence: "Tęcza pojawia się po ___.",                   answer: "deszczu",    hint: "Woda spadająca z chmur" },
    { sentence: "Jabłko i gruszka to ___.",                    answer: "owoce",      hint: "Rosną na drzewach, są słodkie" },
    { sentence: "Marchew i ziemniak to ___.",                  answer: "warzywa",    hint: "Rosną w ziemi lub na łodydze" },
    { sentence: "Muzyk gra na ___.",                           answer: "gitarze",    hint: "Instrument z sześcioma strunami" },
    { sentence: "Czerwony Kapturek szedł do ___.",             answer: "babci",      hint: "Starsza kobieta, mama mamy lub taty" },
    { sentence: "Złota rybka spełnia trzy ___.",               answer: "życzenia",   hint: "Prośby, które chcemy spełnić" },
    { sentence: "___ śpi w norze przez całą zimę.",            answer: "niedźwiedź", hint: "Duże brązowe zwierzę leśne" },
    { sentence: "Mumuś jest taka ___.",                        answer: "słodka",     hint: "Jak cukierek" },
    { sentence: "Maxy ma duży ___ jak Pinokio.",               answer: "nos",        hint: "Gluty" },
    { sentence: "Jojo jest bardzo ___ jak Mumuś.",             answer: "słodki",     hint: "Słodziak" },
    // ── nowe zdania ──
    { sentence: "Sowa poluje w ___.",                          answer: "nocy",       hint: "Kiedy jest ciemno" },
    { sentence: "Niedźwiedź je miód i ___.",                   answer: "jagody",     hint: "Małe leśne owoce" },
    { sentence: "Koń biega po zielonej ___.",                  answer: "łące",       hint: "Duże pole z trawą" },
    { sentence: "___ ma długie uszy i skacze.",                answer: "królik",     hint: "Biały lub szary puszysty zwierzak" },
    { sentence: "Drzewa rosną w ___.",                         answer: "lesie",      hint: "Duże skupisko drzew" },
    { sentence: "Góry są pokryte białym ___.",                 answer: "śniegiem",   hint: "Biała zimowa pokrywa" },
    { sentence: "Odkurzaczem sprzątamy ___.",                  answer: "podłogę",    hint: "To po czym chodzimy w domu" },
    { sentence: "W wannie bierzemy ___.",                      answer: "kąpiel",     hint: "Myjemy się w ciepłej wodzie" },
    { sentence: "Śpimy w wygodnym ___.",                       answer: "łóżku",      hint: "Mebel z materacem i poduszką" },
    { sentence: "Wieszamy ubrania w ___.",                     answer: "szafie",     hint: "Duży mebel z drzwiczkami" },
    { sentence: "Samolot lata wysoko po ___.",                 answer: "niebie",     hint: "Niebieska przestrzeń nad nami" },
    { sentence: "Autobus zatrzymuje się na ___.",              answer: "przystanku", hint: "Miejsce, gdzie wsiadamy" },
    { sentence: "Statek płynie po ___.",                       answer: "wodzie",     hint: "Mokry żywioł, wypełnia oceany" },
    { sentence: "Kierowca prowadzi ___.",                      answer: "samochód",   hint: "Pojazd z czterema kołami" },
    { sentence: "___ nosi koronę na głowie.",                  answer: "król",       hint: "Władca królestwa" },
    { sentence: "Rowerzysta zakłada na głowę ___.",            answer: "kask",       hint: "Chroni głowę przed urazem" },
    { sentence: "Wróbel szuka okruchów ___.",                  answer: "chleba",     hint: "Podstawowy wypiek z mąki" },
    { sentence: "Herbata jest gorąca, a lody są ___.",         answer: "zimne",      hint: "Przeciwieństwo gorącego" },
    { sentence: "Kapelusz zakładamy na ___.",                  answer: "głowę",      hint: "Najwyższa część ciała" },
    { sentence: "___ ma długie uszy i lubi marchewkę.",        answer: "osioł",      hint: "Wygląda jak mały koń, ale krzyczy i-a" },
    { sentence: "Na Wielkanoc szukamy kolorowych ___.",        answer: "jajek",      hint: "Pomalowane, ukryte w ogrodzie" },
    { sentence: "Święty Mikołaj przychodzi w ___.",            answer: "grudniu",    hint: "Ostatni miesiąc roku" },
    { sentence: "Pinokio miał drewniany ___.",                 answer: "nos",        hint: "Rósł gdy kłamał" },
    { sentence: "Smok zieje ___.",                             answer: "ogniem",     hint: "Gorący płomień" },
    { sentence: "___ świeci i ogrzewa Ziemię.",                answer: "słońce",     hint: "Największa gwiazda na naszym niebie" },
    { sentence: "Krowa daje nam świeże ___.",                  answer: "mleko",      hint: "Biały napój od zwierzęcia" },
    { sentence: "___ to mały szczeniak.",                      answer: "piesek",     hint: "Mały, szczekający zwierzak" },
    { sentence: "W zoo oglądamy egzotyczne ___.",              answer: "zwierzęta",  hint: "Lwy, żyrafy, słonie..." },
    { sentence: "Na śniadanie piję ciepłe ___.",               answer: "kakao",      hint: "Brązowy, słodki napój" },
    { sentence: "Z mąki i jajek piecze się ___.",              answer: "ciasto",     hint: "Słodki wypiek z piekarnika" },
    { sentence: "Cytryna jest ___.",                           answer: "kwaśna",     hint: "Przeciwieństwo słodkiej" },
    { sentence: "Cukier jest bardzo ___.",                     answer: "słodki",     hint: "Lubimy go w ciastach i napojach" },
    { sentence: "Sok wyciskamy z ___.",                        answer: "owoców",     hint: "Jabłka, pomarańcze, winogrona..." },
    { sentence: "Piszemy długopisem lub ___.",                 answer: "ołówkiem",   hint: "Można go gumować" },
    { sentence: "Plecak nosimy na ___.",                       answer: "plecach",    hint: "Tylna część tułowia" },
    { sentence: "Linijką mierzymy ___.",                       answer: "długość",    hint: "Ile centymetrów ma coś" },
    { sentence: "Nożyczkami ___ papier.",                      answer: "tniemy",     hint: "Przecinamy na kawałki" },
    { sentence: "Mama i tata to moi ___.",                     answer: "rodzice",    hint: "Osoby, które nas wychowują" },
    { sentence: "Siostra mamy to moja ___.",                   answer: "ciocia",     hint: "Kobieta z rodziny, nie mama" },
    { sentence: "Brat taty to mój ___.",                       answer: "wujek",      hint: "Mężczyzna z rodziny, nie tata" },
    { sentence: "Nosem ___.",                                  answer: "wąchamy",    hint: "Co robimy za pomocą nosa?" },
    { sentence: "Włosy rosną na ___.",                         answer: "głowie",     hint: "Najwyższa część ciała" },
    { sentence: "___ ma czarno-białe pasy.",                   answer: "zebra",      hint: "Afrykańskie zwierzę podobne do konia" },
    { sentence: "Papuga powtarza nasze ___.",                  answer: "słowa",      hint: "To, czym się komunikujemy" },
    { sentence: "Kangur nosi młode w ___.",                    answer: "torbie",     hint: "Kieszeń na brzuchu" },
    { sentence: "Żółw chodzi bardzo ___.",                     answer: "wolno",      hint: "Przeciwieństwo szybko" },
    { sentence: "___ to najwyższe zwierzę na świecie.",        answer: "żyrafa",     hint: "Ma bardzo długą szyję" },
    { sentence: "Bocian stoi na jednej ___.",                  answer: "nodze",      hint: "Część ciała, na której stoimy" },
    { sentence: "Złota ___ spełnia życzenia w bajce.",         answer: "rybka",      hint: "Mały stwór pływający w wodzie" },
    { sentence: "Latem chodzimy na ___.",                      answer: "plażę",      hint: "Piasek i morze" },
];

// Faza 2: Szubienica (50 słów z kategorią)
const HANGMAN_WORDS = [
    { word: "komputer",    category: "Technologia" },
    { word: "dinozaur",    category: "Zwierzęta" },
    { word: "czekolada",   category: "Jedzenie" },
    { word: "parasol",     category: "Przedmioty" },
    { word: "królik",      category: "Zwierzęta" },
    { word: "tramwaj",     category: "Transport" },
    { word: "motocykl",    category: "Transport" },
    { word: "telewizor",   category: "Technologia" },
    { word: "helikopter",  category: "Transport" },
    { word: "piramida",    category: "Budowle" },
    { word: "kalendarz",   category: "Przedmioty" },
    { word: "poduszka",    category: "Dom" },
    { word: "rakieta",     category: "Kosmos" },
    { word: "akwarium",    category: "Przedmioty" },
    { word: "latawiec",    category: "Zabawki" },
    { word: "fortepian",   category: "Muzyka" },
    { word: "krokodyl",    category: "Zwierzęta" },
    { word: "biblioteka",  category: "Miejsca" },
    { word: "lokomotywa",  category: "Transport" },
    { word: "biedronka",   category: "Zwierzęta" },
    { word: "marchewka",   category: "Jedzenie" },
    { word: "samochód",    category: "Transport" },
    { word: "telefon",     category: "Technologia" },
    { word: "kangur",      category: "Zwierzęta" },
    { word: "kwiatek",     category: "Przyroda" },
    { word: "chmura",      category: "Przyroda" },
    { word: "jabłko",      category: "Jedzenie" },
    { word: "rycerz",      category: "Postacie" },
    { word: "syrena",      category: "Bajki" },
    { word: "smok",        category: "Bajki" },
    { word: "korona",      category: "Przedmioty" },
    { word: "zebra",       category: "Zwierzęta" },
    { word: "delfin",      category: "Zwierzęta" },
    { word: "wulkan",      category: "Przyroda" },
    { word: "planeta",     category: "Kosmos" },
    { word: "alfabet",     category: "Szkoła" },
    { word: "pingwin",     category: "Zwierzęta" },
    { word: "kuchnia",     category: "Dom" },
    { word: "kapitan",     category: "Postacie" },
    { word: "robot",       category: "Technologia" },
    { word: "ołówek",      category: "Szkoła" },
    { word: "balon",       category: "Zabawki" },
    { word: "szkoła",      category: "Miejsca" },
    { word: "kompas",      category: "Przedmioty" },
    { word: "wiewiórka",   category: "Zwierzęta" },
    { word: "pizzeria",    category: "Miejsca" },
    { word: "truskawka",   category: "Jedzenie" },
    { word: "papuga",      category: "Zwierzęta" },
    { word: "łódka",       category: "Transport" },
    { word: "zamek",       category: "Budowle" },
];

// Alfabet polski do szubienicy
const POLISH_ALPHABET = [
    'a','ą','b','c','ć','d','e','ę','f','g',
    'h','i','j','k','l','ł','m','n','ń','o',
    'ó','p','r','s','ś','t','u','w','y','z',
    'ź','ż'
];
