/* ═══════════════════════════════════════════
   BAZA DANYCH GRY — pytania i słowa
   ═══════════════════════════════════════════ */

// Faza 1: Uzupełnij brakujące słowo (162 zdania)
const QUESTIONS = [
    { sentence: "Mama piecze ___ na urodziny.",                answer: "tort",       hint: "Coś słodkiego ze świeczkami" },
    { sentence: "W nocy na niebie świeci ___.",                answer: "księżyc",    hint: "Jest okrągły i jasny" },
    { sentence: "Pies macha ___ na powitanie.",                answer: "ogonem",     hint: "Pies ma to z tyłu" },
    { sentence: "Rano jem ___ na śniadanie.",                  answer: "kanapkę",    hint: "Coś z chlebem" },
    { sentence: "___ mieszka w lesie i zbiera orzechy.",       answer: "wiewiórka",  hint: "Małe rude zwierzątko z puszystym ogonem" },
    { sentence: "Dzieci bawią się na ___.",                    answer: "podwórku",   hint: "Miejsce przed domem do zabawy" },
    { sentence: "Zimą pada biały ___.",                        answer: "śnieg",      hint: "Można z niego lepić bałwana" },
    { sentence: "Kot pije ___ z miski.",                       answer: "mleko",      hint: "Biały napój" },
    { sentence: "Tata czyta ___ przed snem.",                  answer: "bajkę",      hint: "Historia z książki" },
    { sentence: "___ pływa w stawie.",                         answer: "żaba",       hint: "Zielona i kumka" },
    { sentence: "W szkole piszemy w ___.",                     answer: "zeszycie",   hint: "Ma kartki w linie lub kratkę" },
    { sentence: "Ptaki budują ___ na drzewie.",                answer: "gniazdo",    hint: "Dom dla ptaków" },
    { sentence: "Samochód jedzie po ___.",                     answer: "drodze",     hint: "Asfaltowa nawierzchnia" },
    { sentence: "Ryby pływają w ___.",                         answer: "morzu",      hint: "Duży zbiornik słonej wody" },
    { sentence: "Słońce wschodzi ___.",                        answer: "rano",       hint: "Pora dnia, kiedy się budzimy" },
    { sentence: "___ daje nam miód.",                          answer: "pszczoła",   hint: "Latający owad w żółto-czarne paski" },
    { sentence: "Na obiad jemy ___ z klopsikami.",             answer: "makaron",    hint: "Długie lub krótkie, gotowane w wodzie" },
    { sentence: "W zimie nosimy czapkę i ___.",                answer: "szalik",     hint: "Owijamy nim szyję" },
    { sentence: "Babcia robi na drutach ___.",                 answer: "sweter",     hint: "Ciepłe ubranie wkładane przez głowę" },
    { sentence: "Listonosz przynosi ___.",                     answer: "listy",      hint: "Wkłada je do skrzynki pocztowej" },
    { sentence: "___ lata i ma kolorowe skrzydła.",            answer: "motyl",      hint: "Lubi siadać na kwiatach" },
    { sentence: "Chłopiec jedzie na ___ do szkoły.",           answer: "rowerze",    hint: "Jednoślad z dwoma kołami" },
    { sentence: "Kura znosi ___ w gnieździe.",                 answer: "jajka",      hint: "Okrągłe, w twardej skorupce" },
    { sentence: "Astronauta leci w ___.",                      answer: "kosmos",     hint: "Tam są gwiazdy i planety" },
    { sentence: "___ ma osiem nóg i plecie sieć.",             answer: "pająk",      hint: "Łapie muchy w pajęczynę" },
    { sentence: "Słoń ma długą ___.",                          answer: "trąbę",      hint: "Używa jej do picia wody" },
    { sentence: "___ jest królem wszystkich zwierząt.",        answer: "lew",        hint: "Duży kot z grzywą" },
    { sentence: "Lekarz leczy ___.",                           answer: "chorych",    hint: "Osoby, które się źle czują" },
    { sentence: "Strażak gasi ___.",                           answer: "pożar",      hint: "Wielki ogień, który się rozprzestrzenia" },
    { sentence: "Pilot steruje ___.",                          answer: "samolotem",  hint: "Wielki pojazd latający" },
    { sentence: "Nauczyciel pisze na ___.",                    answer: "tablicy",    hint: "Czarna lub biała powierzchnia w klasie" },
    { sentence: "W bibliotece wypożyczamy ___.",               answer: "książki",    hint: "Mają kartki i opowiadają historię" },
    { sentence: "___ ma długą szyję i je liście z drzew.",     answer: "żyrafa",     hint: "Najwyższe zwierzę na świecie" },
    { sentence: "Na plaży budujemy zamki z ___.",              answer: "piasku",     hint: "Drobne żółte ziarnka na plaży" },
    { sentence: "Zegar mierzy ___.",                           answer: "czas",       hint: "Godziny, minuty i sekundy" },
    { sentence: "Księżniczka mieszka w wysokim ___.",          answer: "zamku",      hint: "Budowla z wieżyczkami i fosą" },
    { sentence: "___ kroczy wolno i nosi dom na grzbiecie.",   answer: "żółw",       hint: "Gad z twardą skorupą" },
    { sentence: "Kucharz gotuje zupę w ___.",                  answer: "garnku",     hint: "Duże metalowe naczynie z pokrywką" },
    { sentence: "Pociąg jedzie po ___.",                       answer: "torach",     hint: "Metalowe szyny na podłożu" },
    { sentence: "Bałwan ma marchewkę zamiast ___.",            answer: "nosa",       hint: "Środkowa część twarzy, wąchamy nim" },
    { sentence: "Oczami ___.",                                 answer: "widzimy",    hint: "Co robimy za pomocą oczu?" },
    { sentence: "Uszami ___.",                                 answer: "słyszymy",   hint: "Co robimy za pomocą uszu?" },
    { sentence: "Piłkarz kopie ___ do bramki.",                answer: "piłkę",      hint: "Okrągły przedmiot do gry w nogę" },
    { sentence: "Tęcza pojawia się po ___.",                   answer: "deszczu",    hint: "Woda spadająca z chmur" },
    { sentence: "Jabłko i gruszka to ___.",                    answer: "owoce",      hint: "Rosną na drzewach, są słodkie" },
    { sentence: "Marchew i ziemniak to ___.",                  answer: "warzywa",    hint: "Rosną w ziemi lub na łodydze" },
    { sentence: "Muzyk gra na ___.",                           answer: "gitarze",    hint: "Instrument z sześcioma strunami" },
    { sentence: "Czerwony Kapturek szedł do ___.",             answer: "babci",      hint: "Starsza kobieta, mama mamy lub taty" },
    { sentence: "Złota rybka spełnia trzy ___.",               answer: "życzenia",   hint: "Prośby, które chcemy spełnić" },
    { sentence: "___ śpi w norze przez całą zimę.",            answer: "niedźwiedź", hint: "Duże brązowe zwierzę leśne" },
    { sentence: "Mumuś jest taka ___.",                        answer: "słodka",     hint: "Jak cukierek" },
    { sentence: "Maxy ma duży ___ jak Pinokio.",               answer: "nos",        hint: "Gluty" },
    { sentence: "Jojo jest bardzo ___ jak Mumuś.",             answer: "słodki",     hint: "Słodziak" },
    // ── nowe zdania ──
    { sentence: "Sowa poluje w ___.",                          answer: "nocy",       hint: "Kiedy jest ciemno" },
    { sentence: "Niedźwiedź je miód i ___.",                   answer: "jagody",     hint: "Małe leśne owoce" },
    { sentence: "Koń biega po zielonej ___.",                  answer: "łące",       hint: "Duże pole z trawą" },
    { sentence: "___ ma długie uszy i skacze.",                answer: "królik",     hint: "Biały lub szary puszysty zwierzak" },
    { sentence: "Drzewa rosną w ___.",                         answer: "lesie",      hint: "Duże skupisko drzew" },
    { sentence: "Góry są pokryte białym ___.",                 answer: "śniegiem",   hint: "Biała zimowa pokrywa" },
    { sentence: "Odkurzaczem sprzątamy ___.",                  answer: "podłogę",    hint: "To po czym chodzimy w domu" },
    { sentence: "W wannie bierzemy ___.",                      answer: "kąpiel",     hint: "Myjemy się w ciepłej wodzie" },
    { sentence: "Śpimy w wygodnym ___.",                       answer: "łóżku",      hint: "Mebel z materacem i poduszką" },
    { sentence: "Wieszamy ubrania w ___.",                     answer: "szafie",     hint: "Duży mebel z drzwiczkami" },
    { sentence: "Samolot lata wysoko po ___.",                 answer: "niebie",     hint: "Niebieska przestrzeń nad nami" },
    { sentence: "Autobus zatrzymuje się na ___.",              answer: "przystanku", hint: "Miejsce, gdzie wsiadamy" },
    { sentence: "Statek płynie po ___.",                       answer: "wodzie",     hint: "Mokry żywioł, wypełnia oceany" },
    { sentence: "Kierowca prowadzi ___.",                      answer: "samochód",   hint: "Pojazd z czterema kołami" },
    { sentence: "___ nosi koronę na głowie.",                  answer: "król",       hint: "Władca królestwa" },
    { sentence: "Rowerzysta zakłada na głowę ___.",            answer: "kask",       hint: "Chroni głowę przed urazem" },
    { sentence: "Wróbel szuka okruchów ___.",                  answer: "chleba",     hint: "Podstawowy wypiek z mąki" },
    { sentence: "Herbata jest gorąca, a lody są ___.",         answer: "zimne",      hint: "Przeciwieństwo gorącego" },
    { sentence: "Kapelusz zakładamy na ___.",                  answer: "głowę",      hint: "Najwyższa część ciała" },
    { sentence: "___ ma długie uszy i lubi marchewkę.",        answer: "osioł",      hint: "Wygląda jak mały koń, ale krzyczy i-a" },
    { sentence: "Na Wielkanoc szukamy kolorowych ___.",        answer: "jajek",      hint: "Pomalowane, ukryte w ogrodzie" },
    { sentence: "Święty Mikołaj przychodzi w ___.",            answer: "grudniu",    hint: "Ostatni miesiąc roku" },
    { sentence: "Pinokio miał drewniany ___.",                 answer: "nos",        hint: "Rósł gdy kłamał" },
    { sentence: "Smok zieje ___.",                             answer: "ogniem",     hint: "Gorący płomień" },
    { sentence: "___ świeci i ogrzewa Ziemię.",                answer: "słońce",     hint: "Największa gwiazda na naszym niebie" },
    { sentence: "Krowa daje nam świeże ___.",                  answer: "mleko",      hint: "Biały napój od zwierzęcia" },
    { sentence: "___ to mały szczeniak.",                      answer: "piesek",     hint: "Mały, szczekający zwierzak" },
    { sentence: "W zoo oglądamy egzotyczne ___.",              answer: "zwierzęta",  hint: "Lwy, żyrafy, słonie..." },
    { sentence: "Na śniadanie piję ciepłe ___.",               answer: "kakao",      hint: "Brązowy, słodki napój" },
    { sentence: "Z mąki i jajek piecze się ___.",              answer: "ciasto",     hint: "Słodki wypiek z piekarnika" },
    { sentence: "Cytryna jest ___.",                           answer: "kwaśna",     hint: "Przeciwieństwo słodkiej" },
    { sentence: "Cukier jest bardzo ___.",                     answer: "słodki",     hint: "Lubimy go w ciastach i napojach" },
    { sentence: "Sok wyciskamy z ___.",                        answer: "owoców",     hint: "Jabłka, pomarańcze, winogrona..." },
    { sentence: "Piszemy długopisem lub ___.",                 answer: "ołówkiem",   hint: "Można go gumować" },
    { sentence: "Plecak nosimy na ___.",                       answer: "plecach",    hint: "Tylna część tułowia" },
    { sentence: "Linijką mierzymy ___.",                       answer: "długość",    hint: "Ile centymetrów ma coś" },
    { sentence: "Nożyczkami ___ papier.",                      answer: "tniemy",     hint: "Przecinamy na kawałki" },
    { sentence: "Mama i tata to moi ___.",                     answer: "rodzice",    hint: "Osoby, które nas wychowują" },
    { sentence: "Siostra mamy to moja ___.",                   answer: "ciocia",     hint: "Kobieta z rodziny, nie mama" },
    { sentence: "Brat taty to mój ___.",                       answer: "wujek",      hint: "Mężczyzna z rodziny, nie tata" },
    { sentence: "Nosem ___.",                                  answer: "wąchamy",    hint: "Co robimy za pomocą nosa?" },
    { sentence: "Włosy rosną na ___.",                         answer: "głowie",     hint: "Najwyższa część ciała" },
    { sentence: "___ ma czarno-białe pasy.",                   answer: "zebra",      hint: "Afrykańskie zwierzę podobne do konia" },
    { sentence: "Papuga powtarza nasze ___.",                  answer: "słowa",      hint: "To, czym się komunikujemy" },
    { sentence: "Kangur nosi młode w ___.",                    answer: "torbie",     hint: "Kieszeń na brzuchu" },
    { sentence: "Żółw chodzi bardzo ___.",                     answer: "wolno",      hint: "Przeciwieństwo szybko" },
    { sentence: "___ to najwyższe zwierzę na świecie.",        answer: "żyrafa",     hint: "Ma bardzo długą szyję" },
    { sentence: "Bocian stoi na jednej ___.",                  answer: "nodze",      hint: "Część ciała, na której stoimy" },
    { sentence: "Złota ___ spełnia życzenia w bajce.",         answer: "rybka",      hint: "Mały stwór pływający w wodzie" },
    { sentence: "Latem chodzimy na ___.",                      answer: "plażę",      hint: "Piasek i morze" },
    // ── jeszcze więcej zdań ──
    { sentence: "___ pada jesienią z drzew.",                  answer: "liście",     hint: "Żółte i czerwone, spadają na ziemię" },
    { sentence: "Góral mieszka wysoko w ___.",                 answer: "górach",     hint: "Wysokie szczyty pokryte śniegiem" },
    { sentence: "Wiosną kwitną ___.",                          answer: "kwiaty",     hint: "Kolorowe rośliny w ogrodzie" },
    { sentence: "Latem świeci jasne ___.",                     answer: "słońce",     hint: "Gwiazda na naszym niebie" },
    { sentence: "___ pływa w oceanie i tryska wodą.",          answer: "wieloryb",   hint: "Największe zwierzę na świecie" },
    { sentence: "Aktor gra w ___.",                            answer: "filmie",     hint: "Oglądamy go w kinie" },
    { sentence: "Na urodziny dostajemy ___.",                  answer: "prezenty",   hint: "Zapakowane niespodzianki" },
    { sentence: "Kret kopie tunele pod ___.",                  answer: "ziemią",     hint: "Znajduje się pod trawą" },
    { sentence: "Malarz maluje ___.",                          answer: "obrazy",     hint: "Kolorowe dzieła sztuki" },
    { sentence: "Dzwon wisi na wieży ___.",                    answer: "kościoła",   hint: "Budynek z wieżyczką, gdzie się modlą" },
    { sentence: "___ świeci latarnią na morzu.",               answer: "latarnia",   hint: "Wysoka wieża z mocnym światłem" },
    { sentence: "Wiatr wieje i kręci ___.",                    answer: "wiatrakiem", hint: "Ma duże łopaty, które się obracają" },
    { sentence: "Na podłodze leży miękki ___.",                answer: "dywan",      hint: "Ciepła tkanina pod stopami" },
    { sentence: "Pirat szuka zakopanego ___.",                 answer: "skarbu",     hint: "Złoto i klejnoty w skrzyni" },
    { sentence: "Komin wypuszcza ___.",                        answer: "dym",        hint: "Szary obłok lecący w górę" },
    { sentence: "Żaglówka płynie dzięki ___.",                 answer: "wiatrowi",   hint: "Niewidzialna siła, która wieje" },
    { sentence: "___ nosi listy i paczki.",                    answer: "listonosz",  hint: "Pracownik poczty" },
    { sentence: "Okulary zakładamy na ___.",                   answer: "nos",        hint: "Środkowa część twarzy" },
    { sentence: "W akwarium pływają kolorowe ___.",            answer: "rybki",      hint: "Małe wodne zwierzątka" },
    { sentence: "Ciężarówka wiezie ciężki ___.",               answer: "ładunek",    hint: "Towary przewożone pojazdem" },
    { sentence: "Bocian buduje gniazdo na ___.",               answer: "kominie",    hint: "Część domu, z której leci dym" },
    { sentence: "Szewc naprawia stare ___.",                   answer: "buty",       hint: "Nosimy je na stopach" },
    { sentence: "Lisek chowa się w ___.",                      answer: "norze",      hint: "Dziura w ziemi, dom zwierzęcia" },
    { sentence: "Kolibry piją nektar z ___.",                  answer: "kwiatów",    hint: "Kolorowe rośliny pachnące pięknie" },
    { sentence: "Mucha bzyczała i usiadła na ___.",            answer: "ścianie",    hint: "Pionowa powierzchnia w pokoju" },
    { sentence: "W piekarni kupujemy świeży ___.",             answer: "chleb",      hint: "Podstawowy wypiek z mąki" },
    { sentence: "Strażacy jeżdżą czerwonym ___.",             answer: "wozem",      hint: "Pojazd z syreną i drabiną" },
    { sentence: "Na torcie zapalamy ___.",                     answer: "świeczki",   hint: "Małe ogniki na urodzinach" },
    { sentence: "Kreda służy do pisania na ___.",              answer: "tablicy",    hint: "Ciemna powierzchnia w klasie" },
    { sentence: "Biedronka ma czerwone skrzydła z ___.",       answer: "kropkami",   hint: "Małe czarne punkty" },
    { sentence: "Wiosną na drzewach pojawiają się ___.",      answer: "liście",     hint: "Zielone i rosną na gałęziach" },
    { sentence: "Krowa daje nam białe ___.",                   answer: "mleko",      hint: "Zdrowy napój dla dzieci" },
    { sentence: "Na plaży budujemy zamki z ___.",              answer: "piasku",     hint: "Drobne ziarnka na plaży" },
    { sentence: "Dziadek nosi ___ na nosie.",                  answer: "okulary",    hint: "Pomagają lepiej widzieć" },
    { sentence: "Nocą na niebie migoczą ___.",                 answer: "gwiazdy",    hint: "Małe światełka na ciemnym niebie" },
    { sentence: "Ptak śpiewa piękną ___.",                     answer: "piosenkę",   hint: "Melodia z ust lub dzioba" },
    { sentence: "Dzieci jeżdżą do szkoły ___.",               answer: "autobusem",  hint: "Duży pojazd z wieloma miejscami" },
    { sentence: "Na podłodze leży miękki ___.",                answer: "dywan",      hint: "Można po nim chodzić boso" },
    { sentence: "Mama kroi chleb ostrym ___.",                 answer: "nożem",      hint: "Narzędzie z ostrzem" },
    { sentence: "Kotek bawi się kłębkiem ___.",                answer: "wełny",      hint: "Miękka nić zwinięta w kulkę" },
    { sentence: "Jesienią liście zmieniają ___.",              answer: "kolor",      hint: "Z zielonego na żółty i czerwony" },
    { sentence: "Pszczoły mieszkają w ___.",                   answer: "ulu",        hint: "Domek dla owadów robiących miód" },
    { sentence: "Na obiad tata gotuje ___.",                   answer: "zupę",       hint: "Ciepłe danie jedzone łyżką" },
    { sentence: "W parku dzieci karmią ___.",                  answer: "kaczki",     hint: "Ptaki pływające w stawie" },
    { sentence: "Zimą dzieci jeżdżą na ___.",                 answer: "sankach",    hint: "Ślizgają się po śniegu" },
    { sentence: "Na śniadanie piję ciepłe ___.",               answer: "kakao",      hint: "Czekoladowy napój" },
    { sentence: "W ogrodzie rośnie wysoka ___.",               answer: "jabłoń",     hint: "Drzewo z pysznymi owocami" },
    { sentence: "Rano myję zęby ___.",                         answer: "szczoteczką", hint: "Narzędzie do czyszczenia zębów" },
    { sentence: "Pociąg jedzie po ___.",                       answer: "torach",     hint: "Metalowe szyny" },
    { sentence: "Chmury zakryły ___.",                         answer: "słońce",     hint: "Świeci jasno na niebie" },
    { sentence: "Krawiec szyje ubrania ___.",                  answer: "igłą",       hint: "Cienka i ostra, z oczkiem na nić" },
    { sentence: "W akwarium pływają kolorowe ___.",            answer: "rybki",      hint: "Małe zwierzątka wodne" },
    { sentence: "Sowa poluje w ___.",                          answer: "nocy",       hint: "Pora dnia, gdy jest ciemno" },
    { sentence: "Latem chętnie jemy ___.",                     answer: "lody",       hint: "Zimna słodka przekąska" },
    { sentence: "Tęcza ma siedem ___.",                        answer: "kolorów",    hint: "Czerwony, pomarańczowy, żółty..." },
    { sentence: "Ślimak nosi na grzbiecie ___.",               answer: "muszlę",     hint: "Okrągły domek na plecach" },
    { sentence: "W bibliotece wypożyczamy ___.",               answer: "książki",    hint: "Mają strony z tekstem" },
    { sentence: "Wiatr porusza skrzydłami ___.",               answer: "wiatraka",   hint: "Budowla z obracającymi się łopatami" },
    { sentence: "Na lekcji plastyki malujemy ___.",            answer: "farbami",    hint: "Kolorowe substancje do malowania" },
];

// Faza 2: Szubienica (50 słów z kategorią)
const HANGMAN_WORDS = [
    { word: "komputer",    category: "Technologia" },
    { word: "dinozaur",    category: "Zwierzęta" },
    { word: "czekolada",   category: "Jedzenie" },
    { word: "parasol",     category: "Przedmioty" },
    { word: "królik",      category: "Zwierzęta" },
    { word: "tramwaj",     category: "Transport" },
    { word: "motocykl",    category: "Transport" },
    { word: "telewizor",   category: "Technologia" },
    { word: "helikopter",  category: "Transport" },
    { word: "piramida",    category: "Budowle" },
    { word: "kalendarz",   category: "Przedmioty" },
    { word: "poduszka",    category: "Dom" },
    { word: "rakieta",     category: "Kosmos" },
    { word: "akwarium",    category: "Przedmioty" },
    { word: "latawiec",    category: "Zabawki" },
    { word: "fortepian",   category: "Muzyka" },
    { word: "krokodyl",    category: "Zwierzęta" },
    { word: "biblioteka",  category: "Miejsca" },
    { word: "lokomotywa",  category: "Transport" },
    { word: "biedronka",   category: "Zwierzęta" },
    { word: "marchewka",   category: "Jedzenie" },
    { word: "samochód",    category: "Transport" },
    { word: "telefon",     category: "Technologia" },
    { word: "kangur",      category: "Zwierzęta" },
    { word: "kwiatek",     category: "Przyroda" },
    { word: "chmura",      category: "Przyroda" },
    { word: "jabłko",      category: "Jedzenie" },
    { word: "rycerz",      category: "Postacie" },
    { word: "syrena",      category: "Bajki" },
    { word: "smok",        category: "Bajki" },
    { word: "korona",      category: "Przedmioty" },
    { word: "zebra",       category: "Zwierzęta" },
    { word: "delfin",      category: "Zwierzęta" },
    { word: "wulkan",      category: "Przyroda" },
    { word: "planeta",     category: "Kosmos" },
    { word: "alfabet",     category: "Szkoła" },
    { word: "pingwin",     category: "Zwierzęta" },
    { word: "kuchnia",     category: "Dom" },
    { word: "kapitan",     category: "Postacie" },
    { word: "robot",       category: "Technologia" },
    { word: "ołówek",      category: "Szkoła" },
    { word: "balon",       category: "Zabawki" },
    { word: "szkoła",      category: "Miejsca" },
    { word: "kompas",      category: "Przedmioty" },
    { word: "wiewiórka",   category: "Zwierzęta" },
    { word: "pizzeria",    category: "Miejsca" },
    { word: "truskawka",   category: "Jedzenie" },
    { word: "papuga",      category: "Zwierzęta" },
    { word: "łódka",       category: "Transport" },
    { word: "zamek",       category: "Budowle" },
];

// Faza 3: Tłumaczenie z angielskiego na polski (200 słów)
const TRANSLATION_WORDS = [
    // Zwierzęta
    { en: "dog", pl: ["pies"] },
    { en: "cat", pl: ["kot"] },
    { en: "horse", pl: ["koń"] },
    { en: "bird", pl: ["ptak"] },
    { en: "fish", pl: ["ryba"] },
    { en: "bear", pl: ["niedźwiedź", "miś"] },
    { en: "rabbit", pl: ["królik"] },
    { en: "mouse", pl: ["mysz", "myszka"] },
    { en: "cow", pl: ["krowa"] },
    { en: "pig", pl: ["świnia"] },
    { en: "sheep", pl: ["owca"] },
    { en: "duck", pl: ["kaczka"] },
    { en: "chicken", pl: ["kurczak", "kura"] },
    { en: "frog", pl: ["żaba"] },
    { en: "butterfly", pl: ["motyl"] },
    { en: "elephant", pl: ["słoń"] },
    { en: "lion", pl: ["lew"] },
    { en: "tiger", pl: ["tygrys"] },
    { en: "monkey", pl: ["małpa"] },
    { en: "snake", pl: ["wąż"] },
    { en: "wolf", pl: ["wilk"] },
    { en: "fox", pl: ["lis"] },
    { en: "turtle", pl: ["żółw"] },
    { en: "bee", pl: ["pszczoła"] },
    { en: "ant", pl: ["mrówka"] },
    { en: "penguin", pl: ["pingwin"] },
    { en: "dolphin", pl: ["delfin"] },
    { en: "owl", pl: ["sowa"] },
    { en: "parrot", pl: ["papuga"] },
    { en: "spider", pl: ["pająk"] },
    // Jedzenie
    { en: "apple", pl: ["jabłko"] },
    { en: "bread", pl: ["chleb"] },
    { en: "milk", pl: ["mleko"] },
    { en: "cheese", pl: ["ser"] },
    { en: "soup", pl: ["zupa"] },
    { en: "egg", pl: ["jajko", "jajo"] },
    { en: "cake", pl: ["ciasto", "tort"] },
    { en: "ice cream", pl: ["lody"] },
    { en: "banana", pl: ["banan"] },
    { en: "orange", pl: ["pomarańcza"] },
    { en: "strawberry", pl: ["truskawka"] },
    { en: "chocolate", pl: ["czekolada"] },
    { en: "sugar", pl: ["cukier"] },
    { en: "salt", pl: ["sól"] },
    { en: "butter", pl: ["masło"] },
    { en: "water", pl: ["woda"] },
    { en: "juice", pl: ["sok"] },
    { en: "tea", pl: ["herbata"] },
    { en: "rice", pl: ["ryż"] },
    { en: "tomato", pl: ["pomidor"] },
    { en: "potato", pl: ["ziemniak", "kartofel"] },
    { en: "carrot", pl: ["marchewka", "marchew"] },
    { en: "cherry", pl: ["wiśnia"] },
    { en: "grape", pl: ["winogrono"] },
    { en: "lemon", pl: ["cytryna"] },
    // Rodzina
    { en: "mother", pl: ["mama", "matka"] },
    { en: "father", pl: ["tata", "ojciec"] },
    { en: "sister", pl: ["siostra"] },
    { en: "brother", pl: ["brat"] },
    { en: "grandmother", pl: ["babcia"] },
    { en: "grandfather", pl: ["dziadek"] },
    { en: "baby", pl: ["niemowlę", "dziecko"] },
    { en: "family", pl: ["rodzina"] },
    { en: "daughter", pl: ["córka"] },
    { en: "son", pl: ["syn"] },
    { en: "uncle", pl: ["wujek", "wuj"] },
    { en: "aunt", pl: ["ciocia", "ciotka"] },
    { en: "friend", pl: ["przyjaciel", "przyjaciółka", "kolega", "koleżanka"] },
    // Ciało
    { en: "head", pl: ["głowa"] },
    { en: "hand", pl: ["ręka", "dłoń"] },
    { en: "eye", pl: ["oko"] },
    { en: "nose", pl: ["nos"] },
    { en: "ear", pl: ["ucho"] },
    { en: "mouth", pl: ["usta", "buzia"] },
    { en: "tooth", pl: ["ząb"] },
    { en: "hair", pl: ["włosy"] },
    { en: "leg", pl: ["noga"] },
    { en: "foot", pl: ["stopa"] },
    { en: "finger", pl: ["palec"] },
    { en: "heart", pl: ["serce"] },
    // Kolory
    { en: "red", pl: ["czerwony"] },
    { en: "blue", pl: ["niebieski"] },
    { en: "green", pl: ["zielony"] },
    { en: "yellow", pl: ["żółty"] },
    { en: "white", pl: ["biały"] },
    { en: "black", pl: ["czarny"] },
    { en: "pink", pl: ["różowy"] },
    { en: "orange", pl: ["pomarańczowy"] },
    { en: "brown", pl: ["brązowy"] },
    { en: "grey", pl: ["szary"] },
    // Liczby
    { en: "one", pl: ["jeden"] },
    { en: "two", pl: ["dwa"] },
    { en: "three", pl: ["trzy"] },
    { en: "four", pl: ["cztery"] },
    { en: "five", pl: ["pięć"] },
    { en: "six", pl: ["sześć"] },
    { en: "seven", pl: ["siedem"] },
    { en: "eight", pl: ["osiem"] },
    { en: "nine", pl: ["dziewięć"] },
    { en: "ten", pl: ["dziesięć"] },
    // Szkoła
    { en: "book", pl: ["książka"] },
    { en: "pencil", pl: ["ołówek"] },
    { en: "pen", pl: ["długopis"] },
    { en: "school", pl: ["szkoła"] },
    { en: "teacher", pl: ["nauczyciel", "nauczycielka"] },
    { en: "student", pl: ["uczeń", "uczennica"] },
    { en: "desk", pl: ["biurko", "ławka"] },
    { en: "backpack", pl: ["plecak"] },
    { en: "homework", pl: ["praca domowa", "zadanie domowe"] },
    { en: "notebook", pl: ["zeszyt"] },
    { en: "ruler", pl: ["linijka"] },
    { en: "eraser", pl: ["gumka"] },
    { en: "scissors", pl: ["nożyczki"] },
    { en: "letter", pl: ["litera", "list"] },
    // Przyroda
    { en: "tree", pl: ["drzewo"] },
    { en: "flower", pl: ["kwiat", "kwiatek"] },
    { en: "sun", pl: ["słońce"] },
    { en: "moon", pl: ["księżyc"] },
    { en: "star", pl: ["gwiazda"] },
    { en: "rain", pl: ["deszcz"] },
    { en: "snow", pl: ["śnieg"] },
    { en: "wind", pl: ["wiatr"] },
    { en: "cloud", pl: ["chmura"] },
    { en: "river", pl: ["rzeka"] },
    { en: "mountain", pl: ["góra"] },
    { en: "sea", pl: ["morze"] },
    { en: "forest", pl: ["las"] },
    { en: "grass", pl: ["trawa"] },
    { en: "sky", pl: ["niebo"] },
    // Dom
    { en: "house", pl: ["dom"] },
    { en: "door", pl: ["drzwi"] },
    { en: "window", pl: ["okno"] },
    { en: "table", pl: ["stół"] },
    { en: "chair", pl: ["krzesło"] },
    { en: "bed", pl: ["łóżko"] },
    { en: "kitchen", pl: ["kuchnia"] },
    { en: "bathroom", pl: ["łazienka"] },
    { en: "room", pl: ["pokój"] },
    { en: "floor", pl: ["podłoga"] },
    { en: "wall", pl: ["ściana"] },
    { en: "roof", pl: ["dach"] },
    { en: "garden", pl: ["ogród"] },
    { en: "key", pl: ["klucz"] },
    { en: "lamp", pl: ["lampa"] },
    // Ubrania
    { en: "shoe", pl: ["but"] },
    { en: "hat", pl: ["czapka", "kapelusz"] },
    { en: "shirt", pl: ["koszula", "koszulka"] },
    { en: "dress", pl: ["sukienka"] },
    { en: "jacket", pl: ["kurtka"] },
    { en: "socks", pl: ["skarpetki", "skarpety"] },
    { en: "pants", pl: ["spodnie"] },
    { en: "scarf", pl: ["szalik"] },
    { en: "gloves", pl: ["rękawiczki"] },
    { en: "sweater", pl: ["sweter"] },
    // Transport
    { en: "car", pl: ["samochód", "auto"] },
    { en: "bus", pl: ["autobus"] },
    { en: "bicycle", pl: ["rower"] },
    { en: "train", pl: ["pociąg"] },
    { en: "airplane", pl: ["samolot"] },
    { en: "boat", pl: ["łódka", "łódź"] },
    { en: "ship", pl: ["statek", "okręt"] },
    { en: "helicopter", pl: ["helikopter"] },
    { en: "motorcycle", pl: ["motocykl", "motor"] },
    { en: "truck", pl: ["ciężarówka"] },
    // Przymiotniki
    { en: "big", pl: ["duży", "wielki"] },
    { en: "small", pl: ["mały"] },
    { en: "happy", pl: ["szczęśliwy", "wesoły"] },
    { en: "sad", pl: ["smutny"] },
    { en: "fast", pl: ["szybki"] },
    { en: "slow", pl: ["wolny", "powolny"] },
    { en: "hot", pl: ["gorący"] },
    { en: "cold", pl: ["zimny"] },
    { en: "beautiful", pl: ["piękny", "ładny"] },
    { en: "strong", pl: ["silny", "mocny"] },
    { en: "old", pl: ["stary"] },
    { en: "new", pl: ["nowy"] },
    { en: "tall", pl: ["wysoki"] },
    { en: "short", pl: ["krótki", "niski"] },
    { en: "good", pl: ["dobry"] },
    // Czasowniki
    { en: "run", pl: ["biegać", "biec"] },
    { en: "eat", pl: ["jeść"] },
    { en: "sleep", pl: ["spać"] },
    { en: "read", pl: ["czytać"] },
    { en: "write", pl: ["pisać"] },
    { en: "play", pl: ["grać", "bawić się"] },
    { en: "sing", pl: ["śpiewać"] },
    { en: "dance", pl: ["tańczyć"] },
    { en: "swim", pl: ["pływać"] },
    { en: "jump", pl: ["skakać"] },
    { en: "walk", pl: ["chodzić", "iść"] },
    { en: "fly", pl: ["latać", "lecieć"] },
    { en: "draw", pl: ["rysować"] },
    { en: "cook", pl: ["gotować"] },
    { en: "laugh", pl: ["śmiać się"] },
    // Różne
    { en: "clock", pl: ["zegar"] },
    { en: "ball", pl: ["piłka"] },
    { en: "toy", pl: ["zabawka"] },
    { en: "gift", pl: ["prezent"] },
    { en: "picture", pl: ["obrazek", "obraz", "zdjęcie"] },
    { en: "music", pl: ["muzyka"] },
    { en: "game", pl: ["gra"] },
    { en: "story", pl: ["historia", "opowieść", "bajka"] },
    { en: "umbrella", pl: ["parasol", "parasolka"] },
    { en: "bridge", pl: ["most"] },
    { en: "castle", pl: ["zamek"] },
    { en: "king", pl: ["król"] },
    { en: "queen", pl: ["królowa"] },
    { en: "knight", pl: ["rycerz"] },
    { en: "dragon", pl: ["smok"] },
    { en: "rainbow", pl: ["tęcza"] },
    { en: "candle", pl: ["świeca", "świeczka"] },
    { en: "mirror", pl: ["lustro", "zwierciadło"] },
    { en: "soap", pl: ["mydło"] },
    { en: "towel", pl: ["ręcznik"] },
];

// Faza 4: Wiedza o Polsce (50 pytań)
const POLAND_QUIZ = [
    // Stolica i miasta
    { question: "Jak nazywa się stolica Polski?",
      options: ["Kraków", "Warszawa", "Gdańsk", "Wrocław"], correct: 1 },
    { question: "Nad jaką rzeką leży Warszawa?",
      options: ["Odra", "Warta", "Wisła", "Bug"], correct: 2 },
    { question: "Które miasto jest znane z Wawelu?",
      options: ["Warszawa", "Poznań", "Łódź", "Kraków"], correct: 3 },
    { question: "W którym mieście znajduje się Neptun — słynna fontanna?",
      options: ["Gdańsk", "Szczecin", "Kraków", "Lublin"], correct: 0 },
    { question: "Które miasto nazywane jest miastem stu mostów?",
      options: ["Kraków", "Warszawa", "Poznań", "Wrocław"], correct: 3 },
    // Geografia
    { question: "Jak nazywa się najdłuższa rzeka w Polsce?",
      options: ["Odra", "Wisła", "Warta", "Bug"], correct: 1 },
    { question: "Jakie morze oblewa północne wybrzeże Polski?",
      options: ["Morze Śródziemne", "Morze Bałtyckie", "Morze Czarne", "Morze Północne"], correct: 1 },
    { question: "Jak nazywają się najwyższe góry w Polsce?",
      options: ["Beskidy", "Sudety", "Tatry", "Bieszczady"], correct: 2 },
    { question: "Jak nazywa się najwyższy szczyt w Polsce?",
      options: ["Śnieżka", "Rysy", "Babia Góra", "Giewont"], correct: 1 },
    { question: "Ile województw ma Polska?",
      options: ["12", "14", "16", "18"], correct: 2 },
    { question: "Z iloma krajami graniczy Polska?",
      options: ["5", "7", "6", "4"], correct: 1 },
    { question: "Które jezioro jest największe w Polsce?",
      options: ["Śniardwy", "Mamry", "Morskie Oko", "Solina"], correct: 0 },
    { question: "Jak nazywa się pustynia w Polsce?",
      options: ["Pustynia Gobi", "Pustynia Błędowska", "Sahara Polska", "Pustynia Kujawska"], correct: 1 },
    // Symbole narodowe
    { question: "Jaki ptak jest godłem Polski?",
      options: ["Sokół", "Orzeł", "Bocian", "Gołąb"], correct: 1 },
    { question: "Jakie kolory ma flaga Polski?",
      options: ["Biały i czerwony", "Biały i niebieski", "Czerwony i żółty", "Zielony i biały"], correct: 0 },
    { question: "Jak zaczyna się hymn Polski?",
      options: ["Ojczyzno moja", "Jeszcze Polska nie zginęła", "Boże coś Polskę", "Witaj Polsko"], correct: 1 },
    { question: "Kto jest autorem hymnu polskiego?",
      options: ["Adam Mickiewicz", "Józef Wybicki", "Fryderyk Chopin", "Jan Kochanowski"], correct: 1 },
    // Historia i kultura
    { question: "Kto napisał Pana Tadeusza?",
      options: ["Juliusz Słowacki", "Henryk Sienkiewicz", "Adam Mickiewicz", "Bolesław Prus"], correct: 2 },
    { question: "Jak nazywał się polski król, który wygrał bitwę pod Wiedniem?",
      options: ["Zygmunt III", "Jan III Sobieski", "Kazimierz Wielki", "Stefan Batory"], correct: 1 },
    { question: "Kim był Mikołaj Kopernik?",
      options: ["Królem", "Astronomem", "Malarzem", "Poetą"], correct: 1 },
    { question: "Co odkrył Mikołaj Kopernik?",
      options: ["Amerykę", "Że Ziemia krąży wokół Słońca", "Penicylinę", "Elektryczność"], correct: 1 },
    { question: "Kim była Maria Skłodowska-Curie?",
      options: ["Poetką", "Królową", "Naukowcem", "Malarką"], correct: 2 },
    { question: "Fryderyk Chopin był słynnym polskim…",
      options: ["malarzem", "pisarzem", "kompozytorem", "rzeźbiarzem"], correct: 2 },
    { question: "Który polski pisarz otrzymał Nobla za Quo Vadis?",
      options: ["Adam Mickiewicz", "Henryk Sienkiewicz", "Wisława Szymborska", "Czesław Miłosz"], correct: 1 },
    // Tradycje i jedzenie
    { question: "Jakie tradycyjne polskie danie to kieszonki z ciasta z nadzieniem?",
      options: ["Bigos", "Pierogi", "Żurek", "Gołąbki"], correct: 1 },
    { question: "Co to jest bigos?",
      options: ["Zupa z buraków", "Danie z kapusty i mięsa", "Naleśniki", "Ciasto drożdżowe"], correct: 1 },
    { question: "Jak nazywa się tradycyjna polska zupa z buraków?",
      options: ["Żurek", "Barszcz", "Rosół", "Pomidorowa"], correct: 1 },
    { question: "Ile potraw tradycyjnie podaje się na Wigilię?",
      options: ["8", "10", "12", "15"], correct: 2 },
    { question: "Jak nazywa się tradycyjny polski chleb z makiem?",
      options: ["Babka", "Makowiec", "Pączek", "Sernik"], correct: 1 },
    { question: "Jaki tłusty przysmak jemy w Tłusty Czwartek?",
      options: ["Pierogi", "Pączki", "Naleśniki", "Gofry"], correct: 1 },
    // Przyroda
    { question: "Jaki ptak jest symbolem polskiej wsi i wraca wiosną?",
      options: ["Wróbel", "Bocian", "Jaskółka", "Żuraw"], correct: 1 },
    { question: "W którym polskim parku narodowym żyją żubry?",
      options: ["Tatrzański", "Białowieski", "Kampinoski", "Bieszczadzki"], correct: 1 },
    { question: "Jak nazywa się największy ssak lądowy Europy żyjący w Polsce?",
      options: ["Niedźwiedź", "Łoś", "Żubr", "Jeleń"], correct: 2 },
    { question: "Jak nazywa się najstarszy park narodowy w Polsce?",
      options: ["Tatrzański", "Białowieski", "Kampinoski", "Pieniński"], correct: 1 },
    // Sport
    { question: "W jakim sporcie Polska jest bardzo silna na arenie międzynarodowej?",
      options: ["Hokej", "Siatkówka", "Baseball", "Rugby"], correct: 1 },
    { question: "Robert Lewandowski jest słynnym polskim…",
      options: ["tenisistą", "piłkarzem", "koszykarzem", "pływakiem"], correct: 1 },
    { question: "Jak nazywa się najwyższa liga piłkarska w Polsce?",
      options: ["Bundesliga", "Ekstraklasa", "Premier League", "Serie A"], correct: 1 },
    // Zabytki
    { question: "Czym słynie Wieliczka?",
      options: ["Zamkiem", "Kopalnią soli", "Jeziorem", "Górą"], correct: 1 },
    { question: "Gdzie znajduje się zamek krzyżacki — największy ceglany zamek świata?",
      options: ["Kraków", "Malbork", "Warszawa", "Toruń"], correct: 1 },
    { question: "Które polskie miasto słynie z pierników?",
      options: ["Gdańsk", "Poznań", "Toruń", "Lublin"], correct: 2 },
    { question: "Jak nazywa się słynna sala w Zamku Królewskim w Warszawie?",
      options: ["Sala Balowa", "Sala Tronowa", "Sala Rycerska", "Sala Senatorska"], correct: 0 },
    // Ciekawostki
    { question: "W jakim języku mówią Polacy?",
      options: ["Czeskim", "Rosyjskim", "Polskim", "Słowackim"], correct: 2 },
    { question: "Jaka waluta obowiązuje w Polsce?",
      options: ["Euro", "Korona", "Złoty", "Dolar"], correct: 2 },
    { question: "Kiedy Polska obchodzi Święto Niepodległości?",
      options: ["1 maja", "3 maja", "11 listopada", "15 sierpnia"], correct: 2 },
    { question: "Kiedy obchodzimy Święto Konstytucji 3 Maja?",
      options: ["3 marca", "3 maja", "3 lipca", "3 września"], correct: 1 },
    { question: "Jak nazywa się polska waluta grosze?",
      options: ["Centy", "Pensy", "Kopiejki", "Grosze"], correct: 3 },
    { question: "Na jakiej literze zaczyna się nazwa stolicy Polski?",
      options: ["K", "P", "W", "G"], correct: 2 },
    { question: "Ile gwiazdek ma godło Unii Europejskiej, do której należy Polska?",
      options: ["8", "10", "12", "15"], correct: 2 },
    { question: "Jak nazywa się polski taniec narodowy?",
      options: ["Walc", "Polonez", "Tango", "Polka"], correct: 1 },
];

// Alfabet polski do szubienicy
const POLISH_ALPHABET = [
    'a','ą','b','c','ć','d','e','ę','f','g',
    'h','i','j','k','l','ł','m','n','ń','o',
    'ó','p','r','s','ś','t','u','w','y','z',
    'ź','ż'
];
