/* ═══════════════════════════════════════════
   BAZA DANYCH GRY — pytania i słowa
   ═══════════════════════════════════════════ */

// Faza 1: Uzupełnij brakujące słowo (50 zdań)
const QUESTIONS = [
    { sentence: "Mama piecze ___ na urodziny.",                answer: "tort",       hint: "Coś słodkiego ze świeczkami" },
    { sentence: "W nocy na niebie świeci ___.",                answer: "księżyc",    hint: "Jest okrągły i jasny" },
    { sentence: "Pies macha ___ na powitanie.",                answer: "ogonem",     hint: "Pies ma to z tyłu" },
    { sentence: "Rano jem ___ na śniadanie.",                  answer: "kanapkę",    hint: "Coś z chlebem" },
    { sentence: "___ mieszka w lesie i zbiera orzechy.",       answer: "wiewiórka",  hint: "Małe rude zwierzątko z puszystym ogonem" },
    { sentence: "Dzieci bawią się na ___.",                    answer: "podwórku",   hint: "Miejsce przed domem do zabawy" },
    { sentence: "Zimą pada biały ___.",                        answer: "śnieg",      hint: "Można z niego lepić bałwana" },
    { sentence: "Kot pije ___ z miski.",                       answer: "mleko",      hint: "Biały napój" },
    { sentence: "Tata czyta ___ przed snem.",                  answer: "bajkę",      hint: "Historia z książki" },
    { sentence: "___ pływa w stawie.",                         answer: "żaba",       hint: "Zielona i kumka" },
    { sentence: "W szkole piszemy w ___.",                     answer: "zeszycie",   hint: "Ma kartki w linie lub kratkę" },
    { sentence: "Ptaki budują ___ na drzewie.",                answer: "gniazdo",    hint: "Dom dla ptaków" },
    { sentence: "Samochód jedzie po ___.",                     answer: "drodze",     hint: "Asfaltowa nawierzchnia" },
    { sentence: "Ryby pływają w ___.",                         answer: "morzu",      hint: "Duży zbiornik słonej wody" },
    { sentence: "Słońce wschodzi ___.",                        answer: "rano",       hint: "Pora dnia, kiedy się budzimy" },
    { sentence: "___ daje nam miód.",                          answer: "pszczoła",   hint: "Latający owad w żółto-czarne paski" },
    { sentence: "Na obiad jemy ___ z klopsikami.",             answer: "makaron",    hint: "Długie lub krótkie, gotowane w wodzie" },
    { sentence: "W zimie nosimy czapkę i ___.",                answer: "szalik",     hint: "Owijamy nim szyję" },
    { sentence: "Babcia robi na drutach ___.",                 answer: "sweter",     hint: "Ciepłe ubranie wkładane przez głowę" },
    { sentence: "Listonosz przynosi ___.",                     answer: "listy",      hint: "Wkłada je do skrzynki pocztowej" },
    { sentence: "___ lata i ma kolorowe skrzydła.",            answer: "motyl",      hint: "Lubi siadać na kwiatach" },
    { sentence: "Chłopiec jedzie na ___ do szkoły.",           answer: "rowerze",    hint: "Jednoślad z dwoma kołami" },
    { sentence: "Kura znosi ___ w gnieździe.",                 answer: "jajka",      hint: "Okrągłe, w twardej skorupce" },
    { sentence: "Astronauta leci w ___.",                      answer: "kosmos",     hint: "Tam są gwiazdy i planety" },
    { sentence: "___ ma osiem nóg i plecie sieć.",             answer: "pająk",      hint: "Łapie muchy w pajęczynę" },
    { sentence: "Słoń ma długą ___.",                          answer: "trąbę",      hint: "Używa jej do picia wody" },
    { sentence: "___ jest królem wszystkich zwierząt.",        answer: "lew",        hint: "Duży kot z grzywą" },
    { sentence: "Lekarz leczy ___.",                           answer: "chorych",    hint: "Osoby, które się źle czują" },
    { sentence: "Strażak gasi ___.",                           answer: "pożar",      hint: "Wielki ogień, który się rozprzestrzenia" },
    { sentence: "Pilot steruje ___.",                          answer: "samolotem",  hint: "Wielki pojazd latający" },
    { sentence: "Nauczyciel pisze na ___.",                    answer: "tablicy",    hint: "Czarna lub biała powierzchnia w klasie" },
    { sentence: "W bibliotece wypożyczamy ___.",               answer: "książki",    hint: "Mają kartki i opowiadają historię" },
    { sentence: "___ ma długą szyję i je liście z drzew.",     answer: "żyrafa",     hint: "Najwyższe zwierzę na świecie" },
    { sentence: "Na plaży budujemy zamki z ___.",              answer: "piasku",     hint: "Drobne żółte ziarnka na plaży" },
    { sentence: "Zegar mierzy ___.",                           answer: "czas",       hint: "Godziny, minuty i sekundy" },
    { sentence: "Księżniczka mieszka w wysokim ___.",          answer: "zamku",      hint: "Budowla z wieżyczkami i fosą" },
    { sentence: "___ kroczy wolno i nosi dom na grzbiecie.",   answer: "żółw",       hint: "Gad z twardą skorupą" },
    { sentence: "Kucharz gotuje zupę w ___.",                  answer: "garnku",     hint: "Duże metalowe naczynie z pokrywką" },
    { sentence: "Pociąg jedzie po ___.",                       answer: "torach",     hint: "Metalowe szyny na podłożu" },
    { sentence: "Bałwan ma marchewkę zamiast ___.",            answer: "nosa",       hint: "Środkowa część twarzy, wąchamy nim" },
    { sentence: "Oczami ___.",                                 answer: "widzimy",    hint: "Co robimy za pomocą oczu?" },
    { sentence: "Uszami ___.",                                 answer: "słyszymy",   hint: "Co robimy za pomocą uszu?" },
    { sentence: "Piłkarz kopie ___ do bramki.",                answer: "piłkę",      hint: "Okrągły przedmiot do gry w nogę" },
    { sentence: "Tęcza pojawia się po ___.",                   answer: "deszczu",    hint: "Woda spadająca z chmur" },
    { sentence: "Jabłko i gruszka to ___.",                    answer: "owoce",      hint: "Rosną na drzewach, są słodkie" },
    { sentence: "Marchew i ziemniak to ___.",                  answer: "warzywa",    hint: "Rosną w ziemi lub na łodydze" },
    { sentence: "Muzyk gra na ___.",                           answer: "gitarze",    hint: "Instrument z sześcioma strunami" },
    { sentence: "Czerwony Kapturek szedł do ___.",             answer: "babci",      hint: "Starsza kobieta, mama mamy lub taty" },
    { sentence: "Złota rybka spełnia trzy ___.",               answer: "życzenia",   hint: "Prośby, które chcemy spełnić" },
    { sentence: "___ śpi w norze przez całą zimę.",            answer: "niedźwiedź", hint: "Duże brązowe zwierzę leśne" },
    { sentence: "Mumuś jest taka ___.",                        answer: "słodka",     hint: "Jak cukierek" },
    { sentence: "Maxy ma duży ___ jak Pinokio.",               answer: "nos",        hint: "Gluty" },
    { sentence: "Jojo jest bardzo ___ jak Mumuś.",             answer: "słodki",     hint: "Słodziak" },
];

// Faza 2: Szubienica (50 słów)
const HANGMAN_WORDS = [
    { word: "komputer",    hint: "Urządzenie do pracy i zabawy" },
    { word: "dinozaur",    hint: "Wyginęłe zwierzę sprzed milionów lat" },
    { word: "czekolada",   hint: "Słodki brązowy przysmak" },
    { word: "parasol",     hint: "Chroni przed deszczem" },
    { word: "królik",      hint: "Ma długie uszy i skacze" },
    { word: "tramwaj",     hint: "Pojazd miejski na szynach" },
    { word: "motocykl",    hint: "Szybki jednoślad z silnikiem" },
    { word: "telewizor",   hint: "Oglądamy na nim bajki" },
    { word: "helikopter",  hint: "Lata dzięki wirnikowi na górze" },
    { word: "piramida",    hint: "Starożytna budowla w Egipcie" },
    { word: "kalendarz",   hint: "Pokazuje dni i miesiące" },
    { word: "poduszka",    hint: "Kładziemy na niej głowę do snu" },
    { word: "rakieta",     hint: "Leci w kosmos" },
    { word: "akwarium",    hint: "Szklane pudełko z rybkami" },
    { word: "latawiec",    hint: "Lata na wietrze na sznurku" },
    { word: "fortepian",   hint: "Duży instrument z czarno-białymi klawiszami" },
    { word: "krokodyl",    hint: "Duży gad z ostrymi zębami" },
    { word: "biblioteka",  hint: "Miejsce pełne książek" },
    { word: "lokomotywa",  hint: "Ciągnie wagony pociągu" },
    { word: "biedronka",   hint: "Czerwony owad z czarnymi kropkami" },
    { word: "marchewka",   hint: "Pomarańczowe warzywo" },
    { word: "samochód",    hint: "Pojazd z czterema kołami" },
    { word: "telefon",     hint: "Dzwonimy nim do innych" },
    { word: "kangur",      hint: "Skacze i ma torbę na brzuchu" },
    { word: "kwiatek",     hint: "Mała roślinka z kolorowymi płatkami" },
    { word: "chmura",      hint: "Biała i pływa po niebie" },
    { word: "jabłko",      hint: "Okrągły owoc rosnący na drzewie" },
    { word: "rycerz",      hint: "Wojownik w zbroi na koniu" },
    { word: "syrena",      hint: "Istota z bajki z rybim ogonem" },
    { word: "smok",        hint: "Mityczne stworzenie ziejące ogniem" },
    { word: "korona",      hint: "Nosi ją król na głowie" },
    { word: "zebra",       hint: "Zwierzę w czarno-białe pasy" },
    { word: "delfin",      hint: "Inteligentne zwierzę morskie" },
    { word: "wulkan",      hint: "Góra wyrzucająca gorącą lawę" },
    { word: "planeta",     hint: "Ziemia jest jedną z nich" },
    { word: "alfabet",     hint: "Zbiór wszystkich liter" },
    { word: "pingwin",     hint: "Ptak, który nie umie latać" },
    { word: "kuchnia",     hint: "Pokój, w którym gotujemy" },
    { word: "kapitan",     hint: "Dowodzi statkiem lub drużyną" },
    { word: "robot",       hint: "Maszyna, która naśladuje człowieka" },
    { word: "ołówek",      hint: "Piszemy nim, można gumować" },
    { word: "balon",       hint: "Kolorowy, napompowany powietrzem" },
    { word: "szkoła",      hint: "Miejsce, gdzie się uczymy" },
    { word: "kompas",      hint: "Pokazuje kierunki świata" },
    { word: "wiewiórka",   hint: "Rude zwierzątko zbierające orzechy" },
    { word: "pizzeria",    hint: "Restauracja z włoskim daniem" },
    { word: "truskawka",   hint: "Czerwony słodki owoc" },
    { word: "papuga",      hint: "Kolorowy ptak, który powtarza słowa" },
    { word: "łódka",       hint: "Mały pojazd pływający po wodzie" },
    { word: "zamek",       hint: "Budowla z wieżyczkami lub urządzenie w drzwiach" },
];

// Alfabet polski do szubienicy
const POLISH_ALPHABET = [
    'a','ą','b','c','ć','d','e','ę','f','g',
    'h','i','j','k','l','ł','m','n','ń','o',
    'ó','p','r','s','ś','t','u','w','y','z',
    'ź','ż'
];
